name: npm publish

on:
  release:
    types: [created]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Delete node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install yocto-queue as a direct dependency
        run: npm install yocto-queue --save
      - name: Install dependencies
        run: npm install
      - name: List node_modules contents
        run: ls node_modules
      - name: Run tests
        run: npm run pre-test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Delete node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install yocto-queue as a direct dependency
        run: npm install yocto-queue --save
      - name: Install dependencies
        run: npm install
      - name: Publish package to npm
        run: npm run publish-npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  sync-release:
    needs: publish-npm

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Merge master to realese
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: release
          github_token: ${{ github.token }}
